version: '3.8'

services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: rh_app_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Thiara3003.
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=rh_app;Username=postgres;Password=password
      - Jwt__Secret=YourSuperSecretKeyHere
    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  postgres_data: